export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as WhoWeHelp } from './WhoWeHelp'
export { default as HowWeHelp } from './HowWeHelp'
export { default as Testimonials } from './Testimonials'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
